apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-host-1-proc-path-block
  namespace: default
spec:
  nodeSelector:
    matchNames:
      hostName: host-1
  severity: 5
  process:
    matchPaths:
    - path: /bin/sleep # try sleep 1
  action:
    Block
