apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: ew-khp-01
spec:
  nodeSelector:
    matchLabels:
      kubearmorexternalworkloads.security.kubearmor.com: external-workload-01
        #kubernetes.io/hostname: kubearmor-dev
  severity: 5
  file:
    matchPaths:
    - path: /etc/passwd # cat /etc/passwd
  action:
    Audit
