apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: ew-khp-01
spec:
  nodeSelector:
    matchLabels:
      abc: xyz
  severity: 5
  file:
    matchPaths:
    - path: /proc/cpuinfo # cat /etc/passwd
  action:
    Block
