apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-kubearmor-dev-file-path-audit
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: kubearmor-dev
  severity: 5
  file:
    matchPaths:
    - path: /etc/passwd # cat /etc/passwd
  action:
    Audit
